/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cryptoapp.view;

import co.edu.unal.system.Environment;
import co.edu.unal.system.factory.ClearFactory;
import co.edu.unal.system.program.ClearProgram;
import cryptoapp.StandardConsole;
import cryptoapp.StandardPrompt;
import cryptoapp.program.CaesarProgram;
import cryptoapp.programs.factory.CaesarFactory;

/**
 *
 * @author eduarc
 */
public class Crypto extends javax.swing.JFrame {

    /**
     * Creates new form Crypto
     */
    public Crypto() {
        initComponents();
        
        stdout = new StandardConsole(areaOutput);
        prompt = new StandardPrompt(tfCommand);
        
        env = new Environment();
        env.addResource(Environment.FRAME, this);
        env.addResource(Environment.STDOUT, stdout);
        env.addResource(Environment.PROMPT, prompt);
        
        env.addProgram(CaesarProgram.CMD_CAESAR, new CaesarFactory(env));
        env.addProgram(ClearProgram.CMD_CLEAR, new ClearFactory(env));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfCommand = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaOutput = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemExecute = new javax.swing.JMenuItem();
        menuItemExecuteFromFile = new javax.swing.JMenuItem();
        menuItemSave = new javax.swing.JMenuItem();
        menuItemClear = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemExit = new javax.swing.JMenuItem();
        menuCommands = new javax.swing.JMenu();
        menuItemEncrypt = new javax.swing.JMenu();
        menuItemEncryptSubstitution = new javax.swing.JMenuItem();
        menuItemEncryptCaesar = new javax.swing.JMenuItem();
        menuItemEncryptAffine = new javax.swing.JMenuItem();
        menuItemEncryptVigenere = new javax.swing.JMenuItem();
        menuItemEncryptHill = new javax.swing.JMenuItem();
        menuItemEncryptRSA = new javax.swing.JMenuItem();
        menuDecrypt = new javax.swing.JMenu();
        menuItemDecryptSubstitution = new javax.swing.JMenuItem();
        menuItemDecryptCaesar = new javax.swing.JMenuItem();
        menuItemDecryptAffine = new javax.swing.JMenuItem();
        menuItemDecryptVigenere = new javax.swing.JMenuItem();
        menuItemDecryptHill = new javax.swing.JMenuItem();
        menuItemDecryptRSA = new javax.swing.JMenuItem();
        menuCryptoanalisys = new javax.swing.JMenu();
        menuHelp = new javax.swing.JMenu();
        menuItemHelp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        mainPanel.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 0));
        jLabel1.setText("prompt$");

        tfCommand.setBackground(new java.awt.Color(0, 0, 0));
        tfCommand.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        tfCommand.setForeground(new java.awt.Color(204, 204, 204));
        tfCommand.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        tfCommand.setCaretColor(new java.awt.Color(204, 204, 204));
        tfCommand.setDragEnabled(false);
        tfCommand.setSelectionColor(new java.awt.Color(204, 204, 204));
        tfCommand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCommandActionPerformed(evt);
            }
        });

        areaOutput.setEditable(false);
        areaOutput.setBackground(new java.awt.Color(0, 0, 0));
        areaOutput.setBorder(null);
        areaOutput.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        areaOutput.setForeground(new java.awt.Color(204, 204, 204));
        areaOutput.setSelectionColor(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(areaOutput);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Execute");
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCommand, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfCommand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuBar.setBorderPainted(false);

        menuFile.setText("File");

        menuItemExecute.setText("Execute");
        menuItemExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExecuteActionPerformed(evt);
            }
        });
        menuFile.add(menuItemExecute);

        menuItemExecuteFromFile.setText("Execute from File");
        menuFile.add(menuItemExecuteFromFile);

        menuItemSave.setText("Save");
        menuFile.add(menuItemSave);

        menuItemClear.setText("Clear");
        menuFile.add(menuItemClear);
        menuFile.add(jSeparator1);

        menuItemExit.setText("Exit");
        menuFile.add(menuItemExit);

        menuBar.add(menuFile);

        menuCommands.setText("Commands");

        menuItemEncrypt.setText("Encrypt");

        menuItemEncryptSubstitution.setText("Substitution");
        menuItemEncrypt.add(menuItemEncryptSubstitution);

        menuItemEncryptCaesar.setText("Caesar");
        menuItemEncryptCaesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEncryptCaesarActionPerformed(evt);
            }
        });
        menuItemEncrypt.add(menuItemEncryptCaesar);

        menuItemEncryptAffine.setText("Affine");
        menuItemEncrypt.add(menuItemEncryptAffine);

        menuItemEncryptVigenere.setText("Vigenere");
        menuItemEncrypt.add(menuItemEncryptVigenere);

        menuItemEncryptHill.setText("Hill");
        menuItemEncrypt.add(menuItemEncryptHill);

        menuItemEncryptRSA.setText("RSA");
        menuItemEncrypt.add(menuItemEncryptRSA);

        menuCommands.add(menuItemEncrypt);

        menuDecrypt.setText("Decrypt");

        menuItemDecryptSubstitution.setText("Substitution");
        menuDecrypt.add(menuItemDecryptSubstitution);

        menuItemDecryptCaesar.setText("Caesar");
        menuDecrypt.add(menuItemDecryptCaesar);

        menuItemDecryptAffine.setText("Affine");
        menuDecrypt.add(menuItemDecryptAffine);

        menuItemDecryptVigenere.setText("Vigenere");
        menuDecrypt.add(menuItemDecryptVigenere);

        menuItemDecryptHill.setText("Hill");
        menuDecrypt.add(menuItemDecryptHill);

        menuItemDecryptRSA.setText("RSA");
        menuDecrypt.add(menuItemDecryptRSA);

        menuCommands.add(menuDecrypt);

        menuCryptoanalisys.setText("Cryptoanalisys");
        menuCommands.add(menuCryptoanalisys);

        menuBar.add(menuCommands);

        menuHelp.setText("Help");

        menuItemHelp.setText("Help me!");
        menuHelp.add(menuItemHelp);

        menuBar.add(menuHelp);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExecuteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemExecuteActionPerformed

    private void menuItemEncryptCaesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEncryptCaesarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemEncryptCaesarActionPerformed

    private void tfCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCommandActionPerformed
        
        String cmd = tfCommand.getText();
        tfCommand.selectAll();
        stdout.appendln("prompt$ "+cmd);
        env.exec(cmd);
    }//GEN-LAST:event_tfCommandActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tfCommandActionPerformed(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    Environment env;
    StandardConsole stdout;
    StandardPrompt prompt;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane areaOutput;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    public javax.swing.JPanel mainPanel;
    public javax.swing.JMenuBar menuBar;
    public javax.swing.JMenu menuCommands;
    public javax.swing.JMenu menuCryptoanalisys;
    private javax.swing.JMenu menuDecrypt;
    public javax.swing.JMenu menuFile;
    public javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuItemClear;
    public javax.swing.JMenuItem menuItemDecryptAffine;
    public javax.swing.JMenuItem menuItemDecryptCaesar;
    public javax.swing.JMenuItem menuItemDecryptHill;
    public javax.swing.JMenuItem menuItemDecryptRSA;
    public javax.swing.JMenuItem menuItemDecryptSubstitution;
    public javax.swing.JMenuItem menuItemDecryptVigenere;
    private javax.swing.JMenu menuItemEncrypt;
    public javax.swing.JMenuItem menuItemEncryptAffine;
    public javax.swing.JMenuItem menuItemEncryptCaesar;
    public javax.swing.JMenuItem menuItemEncryptHill;
    public javax.swing.JMenuItem menuItemEncryptRSA;
    public javax.swing.JMenuItem menuItemEncryptSubstitution;
    public javax.swing.JMenuItem menuItemEncryptVigenere;
    private javax.swing.JMenuItem menuItemExecute;
    private javax.swing.JMenuItem menuItemExecuteFromFile;
    private javax.swing.JMenuItem menuItemExit;
    public javax.swing.JMenuItem menuItemHelp;
    private javax.swing.JMenuItem menuItemSave;
    private javax.swing.JTextField tfCommand;
    // End of variables declaration//GEN-END:variables
}
