/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cryptoapp.view;

import co.edu.unal.system.Environment;
import co.edu.unal.system.factory.ClearFactory;
import co.edu.unal.system.program.ClearProgram;
import cryptoapp.StandardConsole;
import cryptoapp.StandardPrompt;
import cryptoapp.program.AffineProgram;
import cryptoapp.program.CaesarProgram;
import cryptoapp.program.CryptoAnalyzerProgram;
import cryptoapp.program.DESProgram;
import cryptoapp.program.HillProgram;
import cryptoapp.program.RSAProgram;
import cryptoapp.program.SubstitutionProgram;
import cryptoapp.program.ThreeThreeProgram;
import cryptoapp.program.TwoTwoProgram;
import cryptoapp.program.VigenereProgram;
import cryptoapp.programs.factory.AffineFactory;
import cryptoapp.programs.factory.CaesarFactory;
import cryptoapp.programs.factory.CryptoAnalyzerFactory;
import cryptoapp.programs.factory.DESFactory;
import cryptoapp.programs.factory.HillFactory;
import cryptoapp.programs.factory.RSAFactory;
import cryptoapp.programs.factory.SubstitutionFactory;
import cryptoapp.programs.factory.ThreeThreeFactory;
import cryptoapp.programs.factory.TwoTwoFactory;
import cryptoapp.programs.factory.VigenereFactory;

/**
 *
 * @author eduarc
 */
public class Crypto extends javax.swing.JFrame {

    /**
     * Creates new form Crypto
     */
    public Crypto() {
        initComponents();
        
        stdout = new StandardConsole(areaOutput);
        prompt = new StandardPrompt(tfCommand);
        
        env = new Environment();
        env.addResource(Environment.FRAME, this);
        env.addResource(Environment.STDOUT, stdout);
        env.addResource(Environment.PROMPT, prompt);
        
        env.addProgram(ClearProgram.CMD_CLEAR, new ClearFactory(env));
        env.addProgram(CaesarProgram.CMD_CAESAR, new CaesarFactory(env));
        env.addProgram(AffineProgram.CMD_AFFINE, new AffineFactory(env));
        env.addProgram(VigenereProgram.CMD_VIGENERE, new VigenereFactory(env));
        env.addProgram(SubstitutionProgram.CMD_SUBSTITUTION, new SubstitutionFactory(env));
        env.addProgram(RSAProgram.CMD_RSA, new RSAFactory(env));
        env.addProgram(DESProgram.CMD_DES, new DESFactory(env));
        env.addProgram(HillProgram.CMD_HILL, new HillFactory(env));
        env.addProgram(TwoTwoProgram.CMD_TWO, new TwoTwoFactory(env));
        env.addProgram(ThreeThreeProgram.CMD_THREE, new ThreeThreeFactory(env));
        env.addProgram(CryptoAnalyzerProgram.CMD_CRACK, new CryptoAnalyzerFactory(env));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfCommand = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaOutput = new javax.swing.JTextPane();
        bExec = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemExecute = new javax.swing.JMenuItem();
        menuItemClear = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemExit = new javax.swing.JMenuItem();
        menuCryptosystems = new javax.swing.JMenu();
        menuItemEncrypt = new javax.swing.JMenu();
        unknownMenu = new javax.swing.JMenu();
        encCoCoCaesar = new javax.swing.JMenuItem();
        encCoCoAffine = new javax.swing.JMenuItem();
        encCoCoSubstitution = new javax.swing.JMenuItem();
        encCoCoVigenere = new javax.swing.JMenuItem();
        encCoCoHill = new javax.swing.JMenuItem();
        encCoCoRSA = new javax.swing.JMenuItem();
        encCoCoDES = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        encCoFiCaesar = new javax.swing.JMenuItem();
        encCoFiAffine = new javax.swing.JMenuItem();
        encCoFiSubstitution = new javax.swing.JMenuItem();
        encCoFiVigenere = new javax.swing.JMenuItem();
        encCoFiHill = new javax.swing.JMenuItem();
        encCoFiRSA = new javax.swing.JMenuItem();
        encCoFiDES = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        encFiCoCaesar = new javax.swing.JMenuItem();
        encFiCoAffine = new javax.swing.JMenuItem();
        encFiCoSubstitution = new javax.swing.JMenuItem();
        encFiCoVigenere = new javax.swing.JMenuItem();
        encFiCoHill = new javax.swing.JMenuItem();
        encFiCoRSA = new javax.swing.JMenuItem();
        encFiCoDES = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        encFiFiCaesar = new javax.swing.JMenuItem();
        encFiFiAffine = new javax.swing.JMenuItem();
        encFiFiSubstitution = new javax.swing.JMenuItem();
        encFiFiVigenere = new javax.swing.JMenuItem();
        encFiFiHill = new javax.swing.JMenuItem();
        encFiFiRSA = new javax.swing.JMenuItem();
        encFiFiDES = new javax.swing.JMenuItem();
        menuDecrypt = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        decCoCoCaesar = new javax.swing.JMenuItem();
        decCoCoAffine = new javax.swing.JMenuItem();
        decCoCoSubstitution = new javax.swing.JMenuItem();
        decCoCoVigenere = new javax.swing.JMenuItem();
        decCoCoHill = new javax.swing.JMenuItem();
        decCoCoRSA = new javax.swing.JMenuItem();
        decCoCoDES = new javax.swing.JMenuItem();
        jMenuUnknown1 = new javax.swing.JMenu();
        decCoFiCaesar = new javax.swing.JMenuItem();
        decCoFiAffine = new javax.swing.JMenuItem();
        decCoFiSubstitution = new javax.swing.JMenuItem();
        decCoFiVigenere = new javax.swing.JMenuItem();
        decCoFiHill = new javax.swing.JMenuItem();
        decCoFiRSA = new javax.swing.JMenuItem();
        decCoFiDES = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        decFiCoCaesar = new javax.swing.JMenuItem();
        decFiCoAffine = new javax.swing.JMenuItem();
        decFiCoSubstitution = new javax.swing.JMenuItem();
        decFiCoVigenere = new javax.swing.JMenuItem();
        decFiCoHill = new javax.swing.JMenuItem();
        decFiCoRSA = new javax.swing.JMenuItem();
        decFiCoDES = new javax.swing.JMenuItem();
        jMenuUnknown = new javax.swing.JMenu();
        decFiFiCaesar = new javax.swing.JMenuItem();
        decFiFiAffine = new javax.swing.JMenuItem();
        decFiFiSubstitution = new javax.swing.JMenuItem();
        decFiFiVigenere = new javax.swing.JMenuItem();
        decFiFiHill = new javax.swing.JMenuItem();
        decFiFiRSA = new javax.swing.JMenuItem();
        decFiFiDES = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        encTwoTwoVCS = new javax.swing.JMenuItem();
        encThreeThreeVCS = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        decTwoTwoVCS = new javax.swing.JMenuItem();
        decThreeThreeVCS = new javax.swing.JMenuItem();
        menuCryptoanalysis = new javax.swing.JMenu();
        analysisRSA = new javax.swing.JMenuItem();
        analysisCaesar = new javax.swing.JMenuItem();
        analysisAffine = new javax.swing.JMenuItem();
        analysisSubstitution = new javax.swing.JMenuItem();
        analysisVigenere = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuItemHelp = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        mainPanel.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 0));
        jLabel1.setText("prompt$");

        tfCommand.setBackground(new java.awt.Color(0, 0, 0));
        tfCommand.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        tfCommand.setForeground(new java.awt.Color(204, 204, 204));
        tfCommand.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        tfCommand.setCaretColor(new java.awt.Color(204, 204, 204));
        tfCommand.setDragEnabled(false);
        tfCommand.setSelectionColor(new java.awt.Color(204, 204, 204));
        tfCommand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCommandActionPerformed(evt);
            }
        });

        areaOutput.setEditable(false);
        areaOutput.setBackground(new java.awt.Color(0, 0, 0));
        areaOutput.setBorder(null);
        areaOutput.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        areaOutput.setForeground(new java.awt.Color(204, 204, 204));
        areaOutput.setSelectionColor(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(areaOutput);

        bExec.setBackground(new java.awt.Color(204, 204, 204));
        bExec.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        bExec.setForeground(new java.awt.Color(255, 0, 0));
        bExec.setText("Execute");
        bExec.setContentAreaFilled(false);
        bExec.setFocusable(false);
        bExec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCommand, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bExec, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfCommand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bExec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuBar.setBorderPainted(false);

        menuFile.setText("File");

        menuItemExecute.setText("Execute Command");
        menuItemExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExecuteActionPerformed(evt);
            }
        });
        menuFile.add(menuItemExecute);

        menuItemClear.setText("Clear Console");
        menuItemClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemClearActionPerformed(evt);
            }
        });
        menuFile.add(menuItemClear);
        menuFile.add(jSeparator1);

        menuItemExit.setText("Exit");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuFile.add(menuItemExit);

        menuBar.add(menuFile);

        menuCryptosystems.setText("Cryptosystem");

        menuItemEncrypt.setText("Encrypt");

        unknownMenu.setText("Input Console -> Output Console");

        encCoCoCaesar.setText("Caesar");
        encCoCoCaesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encCoCoCaesarActionPerformed(evt);
            }
        });
        unknownMenu.add(encCoCoCaesar);

        encCoCoAffine.setText("Affine");
        encCoCoAffine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encCoCoAffineActionPerformed(evt);
            }
        });
        unknownMenu.add(encCoCoAffine);

        encCoCoSubstitution.setText("Substitution");
        encCoCoSubstitution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encCoCoSubstitutionActionPerformed(evt);
            }
        });
        unknownMenu.add(encCoCoSubstitution);

        encCoCoVigenere.setText("Vigenere");
        encCoCoVigenere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encCoCoVigenereActionPerformed(evt);
            }
        });
        unknownMenu.add(encCoCoVigenere);

        encCoCoHill.setText("Hill");
        encCoCoHill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encCoCoHillActionPerformed(evt);
            }
        });
        unknownMenu.add(encCoCoHill);

        encCoCoRSA.setText("RSA");
        encCoCoRSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encCoCoRSAActionPerformed(evt);
            }
        });
        unknownMenu.add(encCoCoRSA);

        encCoCoDES.setText("DES");
        encCoCoDES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encCoCoDESActionPerformed(evt);
            }
        });
        unknownMenu.add(encCoCoDES);

        menuItemEncrypt.add(unknownMenu);

        jMenu8.setText("Input Console -> Output File");

        encCoFiCaesar.setText("Caesar");
        encCoFiCaesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encCoFiCaesarActionPerformed(evt);
            }
        });
        jMenu8.add(encCoFiCaesar);

        encCoFiAffine.setText("Affine");
        encCoFiAffine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encCoFiAffineActionPerformed(evt);
            }
        });
        jMenu8.add(encCoFiAffine);

        encCoFiSubstitution.setText("Substitution");
        encCoFiSubstitution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encCoFiSubstitutionActionPerformed(evt);
            }
        });
        jMenu8.add(encCoFiSubstitution);

        encCoFiVigenere.setText("Vigenere");
        encCoFiVigenere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encCoFiVigenereActionPerformed(evt);
            }
        });
        jMenu8.add(encCoFiVigenere);

        encCoFiHill.setText("Hill");
        encCoFiHill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encCoFiHillActionPerformed(evt);
            }
        });
        jMenu8.add(encCoFiHill);

        encCoFiRSA.setText("RSA");
        encCoFiRSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encCoFiRSAActionPerformed(evt);
            }
        });
        jMenu8.add(encCoFiRSA);

        encCoFiDES.setText("DES");
        encCoFiDES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encCoFiDESActionPerformed(evt);
            }
        });
        jMenu8.add(encCoFiDES);

        menuItemEncrypt.add(jMenu8);

        jMenu2.setText("Input File -> Output Console");

        encFiCoCaesar.setText("Caesar");
        encFiCoCaesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encFiCoCaesarActionPerformed(evt);
            }
        });
        jMenu2.add(encFiCoCaesar);

        encFiCoAffine.setText("Affine");
        encFiCoAffine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encFiCoAffineActionPerformed(evt);
            }
        });
        jMenu2.add(encFiCoAffine);

        encFiCoSubstitution.setText("Substitution");
        encFiCoSubstitution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encFiCoSubstitutionActionPerformed(evt);
            }
        });
        jMenu2.add(encFiCoSubstitution);

        encFiCoVigenere.setText("Vigenere");
        encFiCoVigenere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encFiCoVigenereActionPerformed(evt);
            }
        });
        jMenu2.add(encFiCoVigenere);

        encFiCoHill.setText("Hill");
        encFiCoHill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encFiCoHillActionPerformed(evt);
            }
        });
        jMenu2.add(encFiCoHill);

        encFiCoRSA.setText("RSA");
        encFiCoRSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encFiCoRSAActionPerformed(evt);
            }
        });
        jMenu2.add(encFiCoRSA);

        encFiCoDES.setText("DES");
        encFiCoDES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encFiCoDESActionPerformed(evt);
            }
        });
        jMenu2.add(encFiCoDES);

        menuItemEncrypt.add(jMenu2);

        jMenu1.setText("Input File -> Output File");

        encFiFiCaesar.setText("Caesar");
        encFiFiCaesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encFiFiCaesarActionPerformed(evt);
            }
        });
        jMenu1.add(encFiFiCaesar);

        encFiFiAffine.setText("Affine");
        encFiFiAffine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encFiFiAffineActionPerformed(evt);
            }
        });
        jMenu1.add(encFiFiAffine);

        encFiFiSubstitution.setText("Substitution");
        encFiFiSubstitution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encFiFiSubstitutionActionPerformed(evt);
            }
        });
        jMenu1.add(encFiFiSubstitution);

        encFiFiVigenere.setText("Vigenere");
        encFiFiVigenere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encFiFiVigenereActionPerformed(evt);
            }
        });
        jMenu1.add(encFiFiVigenere);

        encFiFiHill.setText("Hill");
        encFiFiHill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encFiFiHillActionPerformed(evt);
            }
        });
        jMenu1.add(encFiFiHill);

        encFiFiRSA.setText("RSA");
        encFiFiRSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encFiFiRSAActionPerformed(evt);
            }
        });
        jMenu1.add(encFiFiRSA);

        encFiFiDES.setText("DES");
        encFiFiDES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encFiFiDESActionPerformed(evt);
            }
        });
        jMenu1.add(encFiFiDES);

        menuItemEncrypt.add(jMenu1);

        menuCryptosystems.add(menuItemEncrypt);

        menuDecrypt.setText("Decrypt");

        jMenu6.setText("Input Console -> Output Console");

        decCoCoCaesar.setText("Caesar");
        decCoCoCaesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decCoCoCaesarActionPerformed(evt);
            }
        });
        jMenu6.add(decCoCoCaesar);

        decCoCoAffine.setText("Affine");
        decCoCoAffine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decCoCoAffineActionPerformed(evt);
            }
        });
        jMenu6.add(decCoCoAffine);

        decCoCoSubstitution.setText("Substitution");
        decCoCoSubstitution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decCoCoSubstitutionActionPerformed(evt);
            }
        });
        jMenu6.add(decCoCoSubstitution);

        decCoCoVigenere.setText("Vigenere");
        decCoCoVigenere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decCoCoVigenereActionPerformed(evt);
            }
        });
        jMenu6.add(decCoCoVigenere);

        decCoCoHill.setText("Hill");
        decCoCoHill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decCoCoHillActionPerformed(evt);
            }
        });
        jMenu6.add(decCoCoHill);

        decCoCoRSA.setText("RSA");
        decCoCoRSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decCoCoRSAActionPerformed(evt);
            }
        });
        jMenu6.add(decCoCoRSA);

        decCoCoDES.setText("DES");
        decCoCoDES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decCoCoDESActionPerformed(evt);
            }
        });
        jMenu6.add(decCoCoDES);

        menuDecrypt.add(jMenu6);

        jMenuUnknown1.setText("Input Console -> Output File");

        decCoFiCaesar.setText("Caesar");
        decCoFiCaesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decCoFiCaesarActionPerformed(evt);
            }
        });
        jMenuUnknown1.add(decCoFiCaesar);

        decCoFiAffine.setText("Affine");
        decCoFiAffine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decCoFiAffineActionPerformed(evt);
            }
        });
        jMenuUnknown1.add(decCoFiAffine);

        decCoFiSubstitution.setText("Substitution");
        decCoFiSubstitution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decCoFiSubstitutionActionPerformed(evt);
            }
        });
        jMenuUnknown1.add(decCoFiSubstitution);

        decCoFiVigenere.setText("Vigenere");
        decCoFiVigenere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decCoFiVigenereActionPerformed(evt);
            }
        });
        jMenuUnknown1.add(decCoFiVigenere);

        decCoFiHill.setText("Hill");
        decCoFiHill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decCoFiHillActionPerformed(evt);
            }
        });
        jMenuUnknown1.add(decCoFiHill);

        decCoFiRSA.setText("RSA");
        decCoFiRSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decCoFiRSAActionPerformed(evt);
            }
        });
        jMenuUnknown1.add(decCoFiRSA);

        decCoFiDES.setText("DES");
        decCoFiDES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decCoFiDESActionPerformed(evt);
            }
        });
        jMenuUnknown1.add(decCoFiDES);

        menuDecrypt.add(jMenuUnknown1);

        jMenu5.setText("Input File -> Output Console");

        decFiCoCaesar.setText("Caesar");
        decFiCoCaesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decFiCoCaesarActionPerformed(evt);
            }
        });
        jMenu5.add(decFiCoCaesar);

        decFiCoAffine.setText("Affine");
        decFiCoAffine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decFiCoAffineActionPerformed(evt);
            }
        });
        jMenu5.add(decFiCoAffine);

        decFiCoSubstitution.setText("Substitution");
        decFiCoSubstitution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decFiCoSubstitutionActionPerformed(evt);
            }
        });
        jMenu5.add(decFiCoSubstitution);

        decFiCoVigenere.setText("Vigenere");
        decFiCoVigenere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decFiCoVigenereActionPerformed(evt);
            }
        });
        jMenu5.add(decFiCoVigenere);

        decFiCoHill.setText("Hill");
        decFiCoHill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decFiCoHillActionPerformed(evt);
            }
        });
        jMenu5.add(decFiCoHill);

        decFiCoRSA.setText("RSA");
        decFiCoRSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decFiCoRSAActionPerformed(evt);
            }
        });
        jMenu5.add(decFiCoRSA);

        decFiCoDES.setText("DES");
        decFiCoDES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decFiCoDESActionPerformed(evt);
            }
        });
        jMenu5.add(decFiCoDES);

        menuDecrypt.add(jMenu5);

        jMenuUnknown.setText("Input File -> Output File");

        decFiFiCaesar.setText("Caesar");
        decFiFiCaesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decFiFiCaesarActionPerformed(evt);
            }
        });
        jMenuUnknown.add(decFiFiCaesar);

        decFiFiAffine.setText("Affine");
        decFiFiAffine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decFiFiAffineActionPerformed(evt);
            }
        });
        jMenuUnknown.add(decFiFiAffine);

        decFiFiSubstitution.setText("Substitution");
        decFiFiSubstitution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decFiFiSubstitutionActionPerformed(evt);
            }
        });
        jMenuUnknown.add(decFiFiSubstitution);

        decFiFiVigenere.setText("Vigenere");
        decFiFiVigenere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decFiFiVigenereActionPerformed(evt);
            }
        });
        jMenuUnknown.add(decFiFiVigenere);

        decFiFiHill.setText("Hill");
        decFiFiHill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decFiFiHillActionPerformed(evt);
            }
        });
        jMenuUnknown.add(decFiFiHill);

        decFiFiRSA.setText("RSA");
        decFiFiRSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decFiFiRSAActionPerformed(evt);
            }
        });
        jMenuUnknown.add(decFiFiRSA);

        decFiFiDES.setText("DES");
        decFiFiDES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decFiFiDESActionPerformed(evt);
            }
        });
        jMenuUnknown.add(decFiFiDES);

        menuDecrypt.add(jMenuUnknown);

        menuCryptosystems.add(menuDecrypt);

        menuBar.add(menuCryptosystems);

        jMenu3.setText("Visual Cryptosystem");

        jMenu4.setText("Encrypt");

        encTwoTwoVCS.setText("(2, 2)-VCS");
        encTwoTwoVCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encTwoTwoVCSActionPerformed(evt);
            }
        });
        jMenu4.add(encTwoTwoVCS);

        encThreeThreeVCS.setText("(3, 3)-VCS");
        encThreeThreeVCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encThreeThreeVCSActionPerformed(evt);
            }
        });
        jMenu4.add(encThreeThreeVCS);

        jMenu3.add(jMenu4);

        jMenu7.setText("Decrypt");

        decTwoTwoVCS.setText("(2, 2)-VCS");
        decTwoTwoVCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decTwoTwoVCSActionPerformed(evt);
            }
        });
        jMenu7.add(decTwoTwoVCS);

        decThreeThreeVCS.setText("(3, 3)-VCS");
        decThreeThreeVCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decThreeThreeVCSActionPerformed(evt);
            }
        });
        jMenu7.add(decThreeThreeVCS);

        jMenu3.add(jMenu7);

        menuBar.add(jMenu3);

        menuCryptoanalysis.setText("Cryptoanalysis");

        analysisRSA.setText("RSA");
        analysisRSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analysisRSAActionPerformed(evt);
            }
        });
        menuCryptoanalysis.add(analysisRSA);

        analysisCaesar.setText("Caesar");
        analysisCaesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analysisCaesarActionPerformed(evt);
            }
        });
        menuCryptoanalysis.add(analysisCaesar);

        analysisAffine.setText("Affine");
        analysisAffine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analysisAffineActionPerformed(evt);
            }
        });
        menuCryptoanalysis.add(analysisAffine);

        analysisSubstitution.setText("Substitution");
        analysisSubstitution.setEnabled(false);
        analysisSubstitution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analysisSubstitutionActionPerformed(evt);
            }
        });
        menuCryptoanalysis.add(analysisSubstitution);

        analysisVigenere.setText("Vigenere");
        analysisVigenere.setEnabled(false);
        analysisVigenere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analysisVigenereActionPerformed(evt);
            }
        });
        menuCryptoanalysis.add(analysisVigenere);

        menuBar.add(menuCryptoanalysis);

        menuHelp.setText("Help");
        menuHelp.setEnabled(false);

        menuItemHelp.setText("Help me!");
        menuHelp.add(menuItemHelp);

        menuBar.add(menuHelp);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExecuteActionPerformed
        tfCommandActionPerformed(evt);
    }//GEN-LAST:event_menuItemExecuteActionPerformed

    private void tfCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCommandActionPerformed
        
        String cmd = tfCommand.getText();
        tfCommand.selectAll();
        stdout.appendln("<font color=\'00FF00\' >prompt$</font> "+cmd);
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                env.exec(cmd);
            }
        });
        t.start();
        //env.exec(cmd);
    }//GEN-LAST:event_tfCommandActionPerformed

    private void bExecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExecActionPerformed
        tfCommandActionPerformed(evt);
    }//GEN-LAST:event_bExecActionPerformed

    private void encFiFiCaesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encFiFiCaesarActionPerformed
        tfCommand.setText(CaesarProgram.CMD_CAESAR+" encrypt offset fin fout");
    }//GEN-LAST:event_encFiFiCaesarActionPerformed

    private void encFiFiAffineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encFiFiAffineActionPerformed
        tfCommand.setText(AffineProgram.CMD_AFFINE+" encrypt a b fin fout");
    }//GEN-LAST:event_encFiFiAffineActionPerformed

    private void encFiFiSubstitutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encFiFiSubstitutionActionPerformed
        tfCommand.setText(SubstitutionProgram.CMD_SUBSTITUTION+" encrypt key fin fout");
    }//GEN-LAST:event_encFiFiSubstitutionActionPerformed

    private void encFiFiVigenereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encFiFiVigenereActionPerformed
        tfCommand.setText(VigenereProgram.CMD_VIGENERE+" encrypt key fin fout");
    }//GEN-LAST:event_encFiFiVigenereActionPerformed

    private void encFiFiHillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encFiFiHillActionPerformed
        tfCommand.setText(HillProgram.CMD_HILL+" encrypt key fin fout");
    }//GEN-LAST:event_encFiFiHillActionPerformed

    private void encFiFiRSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encFiFiRSAActionPerformed
        tfCommand.setText(RSAProgram.CMD_RSA+" encrypt n e fin fout");
    }//GEN-LAST:event_encFiFiRSAActionPerformed

    private void encFiFiDESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encFiFiDESActionPerformed
        tfCommand.setText(DESProgram.CMD_DES+" encrypt key fin fout");
    }//GEN-LAST:event_encFiFiDESActionPerformed

    private void encFiCoCaesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encFiCoCaesarActionPerformed
        tfCommand.setText(CaesarProgram.CMD_CAESAR+" encrypt offset fin");
    }//GEN-LAST:event_encFiCoCaesarActionPerformed

    private void encFiCoAffineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encFiCoAffineActionPerformed
        tfCommand.setText(AffineProgram.CMD_AFFINE+" encrypt a b fin");
    }//GEN-LAST:event_encFiCoAffineActionPerformed

    private void encFiCoSubstitutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encFiCoSubstitutionActionPerformed
        tfCommand.setText(SubstitutionProgram.CMD_SUBSTITUTION+" encrypt key fin");
    }//GEN-LAST:event_encFiCoSubstitutionActionPerformed

    private void encFiCoHillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encFiCoHillActionPerformed
        tfCommand.setText(HillProgram.CMD_HILL+" encrypt key fin");
    }//GEN-LAST:event_encFiCoHillActionPerformed

    private void encFiCoRSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encFiCoRSAActionPerformed
        tfCommand.setText(RSAProgram.CMD_RSA+" encrypt n e fin");
    }//GEN-LAST:event_encFiCoRSAActionPerformed

    private void encFiCoDESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encFiCoDESActionPerformed
        tfCommand.setText(DESProgram.CMD_DES+" encrypt key fin");
    }//GEN-LAST:event_encFiCoDESActionPerformed

    private void encCoFiCaesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encCoFiCaesarActionPerformed
        tfCommand.setText(CaesarProgram.CMD_CAESAR+" encrypt offset in fout");
    }//GEN-LAST:event_encCoFiCaesarActionPerformed

    private void encCoFiAffineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encCoFiAffineActionPerformed
        tfCommand.setText(AffineProgram.CMD_AFFINE+" encrypt a b in fout");
    }//GEN-LAST:event_encCoFiAffineActionPerformed

    private void encCoFiVigenereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encCoFiVigenereActionPerformed
        tfCommand.setText(VigenereProgram.CMD_VIGENERE+" encrypt key in fout");
    }//GEN-LAST:event_encCoFiVigenereActionPerformed

    private void encCoFiHillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encCoFiHillActionPerformed
        tfCommand.setText(HillProgram.CMD_HILL+" encrypt key in fout");
    }//GEN-LAST:event_encCoFiHillActionPerformed

    private void encCoFiSubstitutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encCoFiSubstitutionActionPerformed
        tfCommand.setText(SubstitutionProgram.CMD_SUBSTITUTION+" encrypt key in fout");
    }//GEN-LAST:event_encCoFiSubstitutionActionPerformed

    private void encCoFiRSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encCoFiRSAActionPerformed
        tfCommand.setText(RSAProgram.CMD_RSA+" encrypt n e in fout");
    }//GEN-LAST:event_encCoFiRSAActionPerformed

    private void encCoFiDESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encCoFiDESActionPerformed
        tfCommand.setText(DESProgram.CMD_DES+" encrypt key in fout");
    }//GEN-LAST:event_encCoFiDESActionPerformed

    private void encCoCoCaesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encCoCoCaesarActionPerformed
        tfCommand.setText(CaesarProgram.CMD_CAESAR+" encrypt offset in");
    }//GEN-LAST:event_encCoCoCaesarActionPerformed

    private void encCoCoAffineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encCoCoAffineActionPerformed
        tfCommand.setText(AffineProgram.CMD_AFFINE+" encrypt a b in");
    }//GEN-LAST:event_encCoCoAffineActionPerformed

    private void encCoCoSubstitutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encCoCoSubstitutionActionPerformed
        tfCommand.setText(SubstitutionProgram.CMD_SUBSTITUTION+" encrypt key in");
    }//GEN-LAST:event_encCoCoSubstitutionActionPerformed

    private void encCoCoVigenereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encCoCoVigenereActionPerformed
        tfCommand.setText(VigenereProgram.CMD_VIGENERE+" encrypt key in");
    }//GEN-LAST:event_encCoCoVigenereActionPerformed

    private void encCoCoHillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encCoCoHillActionPerformed
        tfCommand.setText(HillProgram.CMD_HILL+" encrypt key in");
    }//GEN-LAST:event_encCoCoHillActionPerformed

    private void encCoCoRSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encCoCoRSAActionPerformed
        tfCommand.setText(RSAProgram.CMD_RSA+" encrypt n e in");
    }//GEN-LAST:event_encCoCoRSAActionPerformed

    private void encCoCoDESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encCoCoDESActionPerformed
        tfCommand.setText(DESProgram.CMD_DES+" encrypt key in");
    }//GEN-LAST:event_encCoCoDESActionPerformed

    private void decCoCoCaesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decCoCoCaesarActionPerformed
        tfCommand.setText(CaesarProgram.CMD_CAESAR+" decrypt offset in");
    }//GEN-LAST:event_decCoCoCaesarActionPerformed

    private void decCoCoAffineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decCoCoAffineActionPerformed
        tfCommand.setText(AffineProgram.CMD_AFFINE+" decrypt a b in");
    }//GEN-LAST:event_decCoCoAffineActionPerformed

    private void decCoCoSubstitutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decCoCoSubstitutionActionPerformed
        tfCommand.setText(SubstitutionProgram.CMD_SUBSTITUTION+" decrypt key in");
    }//GEN-LAST:event_decCoCoSubstitutionActionPerformed

    private void decCoCoVigenereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decCoCoVigenereActionPerformed
        tfCommand.setText(VigenereProgram.CMD_VIGENERE+" decrypt key in");
    }//GEN-LAST:event_decCoCoVigenereActionPerformed

    private void decCoCoHillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decCoCoHillActionPerformed
        tfCommand.setText(HillProgram.CMD_HILL+" decrypt key in");
    }//GEN-LAST:event_decCoCoHillActionPerformed

    private void decCoCoRSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decCoCoRSAActionPerformed
        tfCommand.setText(RSAProgram.CMD_RSA+" decrypt p q e in");
    }//GEN-LAST:event_decCoCoRSAActionPerformed

    private void decCoCoDESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decCoCoDESActionPerformed
        tfCommand.setText(DESProgram.CMD_DES+" decrypt key in");
    }//GEN-LAST:event_decCoCoDESActionPerformed

    private void decCoFiCaesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decCoFiCaesarActionPerformed
        tfCommand.setText(CaesarProgram.CMD_CAESAR+" decrypt offset in fout");
    }//GEN-LAST:event_decCoFiCaesarActionPerformed

    private void decCoFiAffineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decCoFiAffineActionPerformed
        tfCommand.setText(AffineProgram.CMD_AFFINE+" decrypt a b in fout");
    }//GEN-LAST:event_decCoFiAffineActionPerformed

    private void decCoFiSubstitutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decCoFiSubstitutionActionPerformed
        tfCommand.setText(SubstitutionProgram.CMD_SUBSTITUTION+" decrypt key in fout");
    }//GEN-LAST:event_decCoFiSubstitutionActionPerformed

    private void decCoFiHillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decCoFiHillActionPerformed
        tfCommand.setText(HillProgram.CMD_HILL+" decrypt key in fout");
    }//GEN-LAST:event_decCoFiHillActionPerformed

    private void decCoFiVigenereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decCoFiVigenereActionPerformed
        tfCommand.setText(VigenereProgram.CMD_VIGENERE+" decrypt key in fout");
    }//GEN-LAST:event_decCoFiVigenereActionPerformed

    private void decCoFiRSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decCoFiRSAActionPerformed
        tfCommand.setText(RSAProgram.CMD_RSA+" decrypt p q e in fout");
    }//GEN-LAST:event_decCoFiRSAActionPerformed

    private void decCoFiDESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decCoFiDESActionPerformed
        tfCommand.setText(DESProgram.CMD_DES+" decrypt key in fout");
    }//GEN-LAST:event_decCoFiDESActionPerformed

    private void decFiCoCaesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decFiCoCaesarActionPerformed
        tfCommand.setText(CaesarProgram.CMD_CAESAR+" decrypt offset fin");
    }//GEN-LAST:event_decFiCoCaesarActionPerformed

    private void decFiCoAffineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decFiCoAffineActionPerformed
        tfCommand.setText(AffineProgram.CMD_AFFINE+" decrypt a b fin");
    }//GEN-LAST:event_decFiCoAffineActionPerformed

    private void decFiCoSubstitutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decFiCoSubstitutionActionPerformed
        tfCommand.setText(SubstitutionProgram.CMD_SUBSTITUTION+" decrypt key fin");
    }//GEN-LAST:event_decFiCoSubstitutionActionPerformed

    private void decFiCoVigenereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decFiCoVigenereActionPerformed
        tfCommand.setText(VigenereProgram.CMD_VIGENERE+" decrypt key fin");
    }//GEN-LAST:event_decFiCoVigenereActionPerformed

    private void encFiCoVigenereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encFiCoVigenereActionPerformed
        tfCommand.setText(VigenereProgram.CMD_VIGENERE+" encrypt key fin");
    }//GEN-LAST:event_encFiCoVigenereActionPerformed

    private void decFiCoHillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decFiCoHillActionPerformed
        tfCommand.setText(HillProgram.CMD_HILL+" decrypt key fin");
    }//GEN-LAST:event_decFiCoHillActionPerformed

    private void decFiCoRSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decFiCoRSAActionPerformed
        tfCommand.setText(RSAProgram.CMD_RSA+" decrypt p q e fin");
    }//GEN-LAST:event_decFiCoRSAActionPerformed

    private void decFiCoDESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decFiCoDESActionPerformed
        tfCommand.setText(DESProgram.CMD_DES+" decrypt key fin");
    }//GEN-LAST:event_decFiCoDESActionPerformed

    private void decFiFiCaesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decFiFiCaesarActionPerformed
        tfCommand.setText(CaesarProgram.CMD_CAESAR+" decrypt offset fin fout");
    }//GEN-LAST:event_decFiFiCaesarActionPerformed

    private void decFiFiAffineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decFiFiAffineActionPerformed
        tfCommand.setText(AffineProgram.CMD_AFFINE+" decrypt a b fin fout");
    }//GEN-LAST:event_decFiFiAffineActionPerformed

    private void decFiFiSubstitutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decFiFiSubstitutionActionPerformed
        tfCommand.setText(SubstitutionProgram.CMD_SUBSTITUTION+" decrypt key fin fout");
    }//GEN-LAST:event_decFiFiSubstitutionActionPerformed

    private void decFiFiVigenereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decFiFiVigenereActionPerformed
        tfCommand.setText(VigenereProgram.CMD_VIGENERE+" decrypt key fin fout");
    }//GEN-LAST:event_decFiFiVigenereActionPerformed

    private void decFiFiHillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decFiFiHillActionPerformed
        tfCommand.setText(HillProgram.CMD_HILL+" decrypt key fin fout");
    }//GEN-LAST:event_decFiFiHillActionPerformed

    private void decFiFiRSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decFiFiRSAActionPerformed
        tfCommand.setText(RSAProgram.CMD_RSA+" decrypt p q e fin fout");
    }//GEN-LAST:event_decFiFiRSAActionPerformed

    private void decFiFiDESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decFiFiDESActionPerformed
        tfCommand.setText(DESProgram.CMD_DES+" decrypt key fin fout");
    }//GEN-LAST:event_decFiFiDESActionPerformed

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void encTwoTwoVCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encTwoTwoVCSActionPerformed
        tfCommand.setText(TwoTwoProgram.CMD_TWO+" encrypt secret");
    }//GEN-LAST:event_encTwoTwoVCSActionPerformed

    private void encThreeThreeVCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encThreeThreeVCSActionPerformed
        tfCommand.setText(ThreeThreeProgram.CMD_THREE+" encrypt secret");
    }//GEN-LAST:event_encThreeThreeVCSActionPerformed

    private void decTwoTwoVCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decTwoTwoVCSActionPerformed
        tfCommand.setText(TwoTwoProgram.CMD_TWO+" decrypt share1 share2");
    }//GEN-LAST:event_decTwoTwoVCSActionPerformed

    private void decThreeThreeVCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decThreeThreeVCSActionPerformed
        tfCommand.setText(ThreeThreeProgram.CMD_THREE+" decrypt share1 share2 share3");
    }//GEN-LAST:event_decThreeThreeVCSActionPerformed

    private void menuItemClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemClearActionPerformed
        tfCommand.setText(ClearProgram.CMD_CLEAR);
    }//GEN-LAST:event_menuItemClearActionPerformed

    private void analysisRSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analysisRSAActionPerformed
        tfCommand.setText(CryptoAnalyzerProgram.CMD_CRACK+" rsa n e in");
    }//GEN-LAST:event_analysisRSAActionPerformed

    private void analysisCaesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analysisCaesarActionPerformed
        tfCommand.setText(CryptoAnalyzerProgram.CMD_CRACK+" caesar in");
    }//GEN-LAST:event_analysisCaesarActionPerformed

    private void analysisAffineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analysisAffineActionPerformed
        tfCommand.setText(CryptoAnalyzerProgram.CMD_CRACK+" affine in");
    }//GEN-LAST:event_analysisAffineActionPerformed

    private void analysisSubstitutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analysisSubstitutionActionPerformed
        tfCommand.setText(CryptoAnalyzerProgram.CMD_CRACK+" subs in");
    }//GEN-LAST:event_analysisSubstitutionActionPerformed

    private void analysisVigenereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analysisVigenereActionPerformed
        tfCommand.setText(CryptoAnalyzerProgram.CMD_CRACK+" vigenere in");
    }//GEN-LAST:event_analysisVigenereActionPerformed

    Environment env;
    StandardConsole stdout;
    StandardPrompt prompt;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem analysisAffine;
    private javax.swing.JMenuItem analysisCaesar;
    private javax.swing.JMenuItem analysisRSA;
    private javax.swing.JMenuItem analysisSubstitution;
    private javax.swing.JMenuItem analysisVigenere;
    private javax.swing.JTextPane areaOutput;
    private javax.swing.JButton bExec;
    private javax.swing.JMenuItem decCoCoAffine;
    private javax.swing.JMenuItem decCoCoCaesar;
    private javax.swing.JMenuItem decCoCoDES;
    private javax.swing.JMenuItem decCoCoHill;
    private javax.swing.JMenuItem decCoCoRSA;
    private javax.swing.JMenuItem decCoCoSubstitution;
    private javax.swing.JMenuItem decCoCoVigenere;
    private javax.swing.JMenuItem decCoFiAffine;
    private javax.swing.JMenuItem decCoFiCaesar;
    private javax.swing.JMenuItem decCoFiDES;
    private javax.swing.JMenuItem decCoFiHill;
    private javax.swing.JMenuItem decCoFiRSA;
    private javax.swing.JMenuItem decCoFiSubstitution;
    private javax.swing.JMenuItem decCoFiVigenere;
    private javax.swing.JMenuItem decFiCoAffine;
    private javax.swing.JMenuItem decFiCoCaesar;
    private javax.swing.JMenuItem decFiCoDES;
    private javax.swing.JMenuItem decFiCoHill;
    private javax.swing.JMenuItem decFiCoRSA;
    private javax.swing.JMenuItem decFiCoSubstitution;
    private javax.swing.JMenuItem decFiCoVigenere;
    private javax.swing.JMenuItem decFiFiAffine;
    private javax.swing.JMenuItem decFiFiCaesar;
    private javax.swing.JMenuItem decFiFiDES;
    private javax.swing.JMenuItem decFiFiHill;
    private javax.swing.JMenuItem decFiFiRSA;
    private javax.swing.JMenuItem decFiFiSubstitution;
    private javax.swing.JMenuItem decFiFiVigenere;
    private javax.swing.JMenuItem decThreeThreeVCS;
    private javax.swing.JMenuItem decTwoTwoVCS;
    private javax.swing.JMenuItem encCoCoAffine;
    private javax.swing.JMenuItem encCoCoCaesar;
    private javax.swing.JMenuItem encCoCoDES;
    private javax.swing.JMenuItem encCoCoHill;
    private javax.swing.JMenuItem encCoCoRSA;
    private javax.swing.JMenuItem encCoCoSubstitution;
    private javax.swing.JMenuItem encCoCoVigenere;
    private javax.swing.JMenuItem encCoFiAffine;
    private javax.swing.JMenuItem encCoFiCaesar;
    private javax.swing.JMenuItem encCoFiDES;
    private javax.swing.JMenuItem encCoFiHill;
    private javax.swing.JMenuItem encCoFiRSA;
    private javax.swing.JMenuItem encCoFiSubstitution;
    private javax.swing.JMenuItem encCoFiVigenere;
    private javax.swing.JMenuItem encFiCoAffine;
    private javax.swing.JMenuItem encFiCoCaesar;
    private javax.swing.JMenuItem encFiCoDES;
    private javax.swing.JMenuItem encFiCoHill;
    private javax.swing.JMenuItem encFiCoRSA;
    private javax.swing.JMenuItem encFiCoSubstitution;
    private javax.swing.JMenuItem encFiCoVigenere;
    private javax.swing.JMenuItem encFiFiAffine;
    private javax.swing.JMenuItem encFiFiCaesar;
    private javax.swing.JMenuItem encFiFiDES;
    private javax.swing.JMenuItem encFiFiHill;
    private javax.swing.JMenuItem encFiFiRSA;
    private javax.swing.JMenuItem encFiFiSubstitution;
    private javax.swing.JMenuItem encFiFiVigenere;
    private javax.swing.JMenuItem encThreeThreeVCS;
    private javax.swing.JMenuItem encTwoTwoVCS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu jMenuUnknown;
    private javax.swing.JMenu jMenuUnknown1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    public javax.swing.JPanel mainPanel;
    public javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCryptoanalysis;
    public javax.swing.JMenu menuCryptosystems;
    private javax.swing.JMenu menuDecrypt;
    public javax.swing.JMenu menuFile;
    public javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuItemClear;
    private javax.swing.JMenu menuItemEncrypt;
    private javax.swing.JMenuItem menuItemExecute;
    private javax.swing.JMenuItem menuItemExit;
    public javax.swing.JMenuItem menuItemHelp;
    private javax.swing.JTextField tfCommand;
    private javax.swing.JMenu unknownMenu;
    // End of variables declaration//GEN-END:variables
}
